ASSUMEROLE=arn:aws:iam::${account-id}:role/tf-web-prd-iam-bastion-role

# IAM Group
IAM_AUTHORIZED_GROUPS="tf-iam-infra-group"
SUDOERS_GROUPS="tf-iam-infra-group"
LOCAL_MARKER_GROUPS="tf-iam-infra-group"

# Remove or set to 0 if you rare dome with configration
# To change the interval of the sync change this file
# /etc/cron.d/import_users
DONOTSYNC=0
